Repository CachaSan10/repositorio-tp2, pull requests merged in 2023-05, with the labels that each got.

#54 Se realizo el alta de agregar consejo
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/controller/ConsejoController.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/listas/ListaConsejoSalud.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/model/Consejo.java
  Tp2_Grupo30/src/main/resources/static/css/style.css
  Tp2_Grupo30/src/main/resources/templates/agregar-consejo.html
  Tp2_Grupo30/src/main/resources/templates/consejo-salud.html
Labels: Fusión de ramas

#62 Se trabajo en servicios.html y nuevo_servicio.html. Se creo el
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/controller/IndexController.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/controller/ServicioController.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/listas/ListaServicio.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/model/Servicio.java
  Tp2_Grupo30/src/main/resources/templates/layouts/nav.html
  Tp2_Grupo30/src/main/resources/templates/nuevo_servicio.html
  Tp2_Grupo30/src/main/resources/templates/servicios.html
Labels: Fusión de ramas

#65 Se trabajo con el css de servcios.html y nuevo_servicio.html.
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/controller/ServicioController.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/listas/ListaServicio.java
  Tp2_Grupo30/src/main/resources/static/css/style.css
  Tp2_Grupo30/src/main/resources/templates/nuevo_servicio.html
  Tp2_Grupo30/src/main/resources/templates/servicios.html
Labels: Fusión de ramas, Diseño css

#66 Se realizo cambios en los archivos servicios.html y nuevo_servicio.html
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/listas/ListaServicio.java
  Tp2_Grupo30/src/main/resources/templates/nuevo_servicio.html
  Tp2_Grupo30/src/main/resources/templates/servicios.html
Labels: Diseño html, Fusión de ramas

#68 modificacion del archivo sucursalController, ListaSucursales
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/controller/SucursalesController.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/listas/ListaSucursal.java
Labels: Crear archivo, Crear Rama, Crear Clase del controller

#69 modificacion de sucursales Id(codigo)
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/controller/SucursalesController.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/listas/ListaSucursal.java
  Tp2_Grupo30/src/main/resources/templates/nueva_sucursal.html
  Tp2_Grupo30/src/main/resources/templates/sucursales.html
Labels: Fusión de ramas, Modificar archivo

#71 Se va a modificar los horarios de la clase servicio
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/model/Servicio.java
Labels: Crear Rama

#72 Crear horario
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/controller/ServicioController.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/listas/ListaServicio.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/model/Servicio.java
  Tp2_Grupo30/src/main/resources/templates/nuevo_servicio.html
  Tp2_Grupo30/src/main/resources/templates/servicios.html
Labels: Fusión de ramas

#75 Se agregaron comentarios al codigo
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/listas/ListaServicio.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/model/Servicio.java
  Tp2_Grupo30/src/main/resources/static/css/style.css
Labels: Fusión de ramas, Agregar Comentarios

#76 modificacion en el archivo sucursales.html y style.css
  Tp2_Grupo30/src/main/resources/static/css/style.css
  Tp2_Grupo30/src/main/resources/templates/sucursales.html
Labels: Modificar archivo

#79 Cachambi nahuel consejo bootstrap
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/listas/ListaConsejo.java
  Tp2_Grupo30/src/main/resources/static/css/style.css
  Tp2_Grupo30/src/main/resources/templates/consejos.html
  Tp2_Grupo30/src/main/resources/templates/layouts/header.html
  Tp2_Grupo30/src/main/resources/templates/nuevo_consejo.html
Labels: Fusión de ramas

#80 Se modifico el nav con las etiquetas bootstrap para que sea responsivo.
  Tp2_Grupo30/src/main/resources/static/css/style.css
  Tp2_Grupo30/src/main/resources/templates/consejos.html
  Tp2_Grupo30/src/main/resources/templates/layouts/nav.html
Labels: Fusión de ramas

#85 @Component en las clases Consejo y ListaConsejo.
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/controller/ConsejoController.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/listas/ListaConsejo.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/model/Consejo.java
Labels: Fusión de ramas

#86 Implementar bootstrap en servicios.html y nuevo_servicio.html
  Tp2_Grupo30/src/main/resources/templates/nuevo_servicio.html
  Tp2_Grupo30/src/main/resources/templates/servicios.html
Labels: crear archivo responsive

#90 Se implemento bootstrap en el index.html
  Tp2_Grupo30/src/main/resources/templates/index.html
Labels: Fusión de ramas, crear archivo responsive

#91 Cachambi nahuel consejo bootstrap
  Tp2_Grupo30/pom.xml
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/controller/ConsejoController.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/model/Consejo.java
  Tp2_Grupo30/src/main/resources/messages.properties
  Tp2_Grupo30/src/main/resources/static/css/style.css
  Tp2_Grupo30/src/main/resources/templates/consejos.html
  Tp2_Grupo30/src/main/resources/templates/nuevo_consejo.html
Labels: Fusión de ramas

#93 Se implemento inyeccion de dependencias en las clases Servicio,
  Tp2_Grupo30/pom.xml
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/controller/ServicioController.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/listas/ListaServicio.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/model/Servicio.java
Labels: Fusión de ramas, Introducir Anotaciones e Injeccion de Dependencias
