Repository CachaSan10/repositorio-tp2, pull requests merged in 2023-06, with the labels that each got.

#99 Se trabajo con validaciones en el formulario nuevo servicio.
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/controller/ServicioController.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/listas/ListaServicio.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/model/Servicio.java
  Tp2_Grupo30/src/main/resources/static/css/style.css
  Tp2_Grupo30/src/main/resources/templates/index.html
  Tp2_Grupo30/src/main/resources/templates/nuevo_servicio.html
  Tp2_Grupo30/src/main/resources/templates/servicios.html
Labels: Fusión de ramas, Implementar Validaciones

#100 Cachambi nahuel consejo bootstrap
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/controller/ConsejoController.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/listas/ListaConsejo.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/model/Consejo.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/util/UploadFile.java
  Tp2_Grupo30/src/main/resources/application.properties
  Tp2_Grupo30/src/main/resources/messages.properties
  Tp2_Grupo30/src/main/resources/templates/consejos.html
  Tp2_Grupo30/src/main/resources/templates/nuevo_consejo.html
Labels: Fusión de ramas

#104 Modificacion en el archivo "nueva_sucursal.html"
  Tp2_Grupo30/src/main/resources/templates/nueva_sucursal.html
Labels: Modificar archivo

#114 Consejo service
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/controller/ConsejoController.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/listas/ListaConsejo.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/service/IConsejoService.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/service/imp/ConsejoServiceImp.java
Labels: Fusión de ramas

#118 crear e implementar la capa service en servicio.
  Tp2_Grupo30/bin/.gitignore
  Tp2_Grupo30/bin/pom.xml
  Tp2_Grupo30/bin/src/main/resources/application.properties
  Tp2_Grupo30/bin/src/main/resources/static/images/Logo-Puppis.jpg
  Tp2_Grupo30/bin/src/main/resources/static/images/alimentos.jpg
  Tp2_Grupo30/bin/src/main/resources/static/images/perro_mejor-mascota.jpg
  Tp2_Grupo30/bin/src/main/resources/templates/Contáctanos.html
  Tp2_Grupo30/bin/src/main/resources/templates/consejoDeSalud.html
  Tp2_Grupo30/bin/src/main/resources/templates/index.html
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/controller/ServicioController.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/listas/ListaServicio.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/model/Servicio.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/service/IServicioService.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/service/imp/ServicioServiceImp.java
Labels: Fusión de ramas

#121 Modificacion del archivo SucursalServiceImp
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/service/imp/SucursalServiceImp.java
Labels: Modificar archivo

#122 Agregar comentarios en servicios y modificar nuevoservicio.html
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/controller/ServicioController.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/model/Servicio.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/service/imp/ServicioServiceImp.java
Labels: bug, Fusión de ramas, Agregar Comentarios

#124 Modificacion del archivo "SucursalesController.java"
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/controller/SucursalesController.java
Labels: Modificar archivo

#134 Modificar nav, crear gestiondatos.html y su controller
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/controller/GestionDatosController.java
  Tp2_Grupo30/src/main/resources/static/css/style.css
  Tp2_Grupo30/src/main/resources/templates/gestiondatos.html
  Tp2_Grupo30/src/main/resources/templates/layouts/nav.html
Labels: Fusión de ramas

#140 Se agrego html para gestionar sucursales.
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/controller/SucursalesController.java
  Tp2_Grupo30/src/main/resources/templates/gestion_sucursales.html
  Tp2_Grupo30/src/main/resources/templates/gestiondatos.html
Labels: Fusión de ramas

#141 Eliminar el button "modificar" y "eliminar" del archivo sucursales.html
  Tp2_Grupo30/src/main/resources/templates/sucursales.html
Labels: Modificar archivo

#142 Responsable: Nahuel Alberto Cachambi
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/controller/ConsejoController.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/controller/GestionDatosController.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/service/IConsejoService.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/service/imp/ConsejoServiceImp.java
  Tp2_Grupo30/src/main/resources/static/css/style.css
  Tp2_Grupo30/src/main/resources/templates/consejos.html
  Tp2_Grupo30/src/main/resources/templates/contacto.html
  Tp2_Grupo30/src/main/resources/templates/gestion_consejos.html
  Tp2_Grupo30/src/main/resources/templates/gestion_datos.html
Labels: Fusión de ramas

#147 Responsable: Nahuel Alberto Cachambi
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/controller/ConsejoController.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/entity/Consejo.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/listas/ListaConsejo.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/repository/IConsejoRepository.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/service/IConsejoService.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/service/imp/ConsejoServiceImp.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/service/imp/ConsejoServiceMysqlImp.java
  Tp2_Grupo30/src/main/resources/application.properties
  Tp2_Grupo30/src/main/resources/import.sql
  Tp2_Grupo30/src/main/resources/templates/gestion_consejos.html
  Tp2_Grupo30/src/main/resources/templates/gestion_datos.html
Labels: Fusión de ramas

#155 Responsable: Villena Franco
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/entity/Sucursal.java
  Tp2_Grupo30/src/main/resources/templates/nueva_sucursal.html
  Tp2_Grupo30/src/main/resources/templates/sucursales.html
Labels: Diseño html, Implementar Validaciones

#157 Responsable: Villena Franco
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/controller/SucursalesController.java
  Tp2_Grupo30/src/main/resources/application.properties
Labels: Implementar Validaciones

#159 Responsable: VillenaFranco
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/controller/SucursalesController.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/repository/ISucursalRepository.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/service/ISucursalService.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/service/imp/SucursalServiceImp.java
  Tp2_Grupo30/src/main/resources/application.properties
  Tp2_Grupo30/src/main/resources/templates/gestion_sucursales.html
  Tp2_Grupo30/src/main/resources/templates/nueva_provincia.html
  Tp2_Grupo30/src/main/resources/templates/nueva_sucursal.html
  Tp2_Grupo30/src/main/resources/templates/provincias.html
  Tp2_Grupo30/src/main/resources/templates/sucursales.html
Labels: Diseño html, Modificar archivo

#166 user: Nahuel277
  Tp2_Grupo30/src/main/resources/templates/gestion_sucursales.html
  Tp2_Grupo30/src/main/resources/templates/nueva_provincia.html
  Tp2_Grupo30/src/main/resources/templates/nueva_sucursal.html
  Tp2_Grupo30/src/main/resources/templates/provincias.html
Labels: Modificar archivo

#169 Producto repository
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/entity/Categoria.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/entity/Producto.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/entity/Provincia.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/listas/ListaProducto.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/listas/ListaSucursal.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/repository/ICategoriaRepository.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/repository/IProductoRepository.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/service/ICategoriaService.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/service/IProductoService.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/service/ISucursalService.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/service/imp/CategoriaServiceMysqlImp.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/service/imp/ProductoServiceImp.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/service/imp/ProductoServiceMysqlImp.java
Labels: Fusión de ramas

#172 Responsable: Nahuel Alberto Cachambi
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/controller/CategoriaController.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/controller/ConsejoController.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/controller/GestionDatosController.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/controller/ProductoController.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/controller/ProvinciaController.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/entity/Categoria.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/entity/Producto.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/listas/ListaProducto.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/service/ICategoriaService.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/service/IConsejoService.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/service/IProductoService.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/service/imp/CategoriaServiceMysqlImp.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/service/imp/ConsejoServiceImp.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/service/imp/ConsejoServiceMysqlImp.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/service/imp/ProductoServiceImp.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/service/imp/ProductoServiceMysqlImp.java
  Tp2_Grupo30/src/main/resources/application.properties
  Tp2_Grupo30/src/main/resources/templates/gestion_categorias.html
  Tp2_Grupo30/src/main/resources/templates/gestion_datos.html
  Tp2_Grupo30/src/main/resources/templates/gestion_productos.html
  Tp2_Grupo30/src/main/resources/templates/nuevo-producto.html
Labels: Fusión de ramas

#174 Producto repository
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/controller/CategoriaController.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/controller/ProductoController.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/entity/Producto.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/service/imp/CategoriaServiceMysqlImp.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/service/imp/ProductoServiceImp.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/service/imp/ProductoServiceMysqlImp.java
  Tp2_Grupo30/src/main/resources/application.properties
  Tp2_Grupo30/src/main/resources/templates/gestion_productos.html
  Tp2_Grupo30/src/main/resources/templates/layouts/nav.html
  Tp2_Grupo30/src/main/resources/templates/nueva_categoria.html
  Tp2_Grupo30/src/main/resources/templates/nuevo-producto.html
  Tp2_Grupo30/src/main/resources/templates/productos.html
Labels: Fusión de ramas

#176 Responsable: Moyata, Lautaro Nahuel
  Tp2_Grupo30/src/main/resources/templates/nueva_sucursal.html
Labels: Modificar archivo

#179 Producto repository
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/controller/CategoriaController.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/controller/ProductoController.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/entity/Categoria.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/entity/Producto.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/service/imp/ProductoServiceMysqlImp.java
  Tp2_Grupo30/src/main/resources/messages.properties
  Tp2_Grupo30/src/main/resources/templates/gestion_categorias.html
  Tp2_Grupo30/src/main/resources/templates/gestion_productos.html
  Tp2_Grupo30/src/main/resources/templates/nueva_categoria.html
  Tp2_Grupo30/src/main/resources/templates/nuevo-producto.html
Labels: Fusión de ramas

#178 Mostrar las sucursales que están entre una fechaInicio y fechaFin
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/controller/SucursalesController.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/repository/ISucursalRepository.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/service/ISucursalService.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/service/imp/SucursalServiceImp.java
  Tp2_Grupo30/src/main/resources/templates/nueva_provincia.html
  Tp2_Grupo30/src/main/resources/templates/sucursales.html
Labels: Modificar archivo

#180 Cambiar el nombre de archivo
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/controller/SucursalController.java
Labels: Modificar archivo

#182 Mostrar las sucursales fechaInicio y fechaFin - actualizacion
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/controller/SucursalController.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/service/imp/SucursalServiceImp.java
  Tp2_Grupo30/src/main/resources/templates/gestion_sucursales.html
  Tp2_Grupo30/src/main/resources/templates/nueva_sucursal.html
  Tp2_Grupo30/src/main/resources/templates/provincias.html
  Tp2_Grupo30/src/main/resources/templates/sucursales.html
Labels: Modificar archivo

#183 Servicio repository
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/controller/CategoriaController.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/controller/EmpleadoController.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/controller/ServicioController.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/entity/Empleado.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/entity/Servicio.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/listas/ListaServicio.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/repository/IEmpleadoRepository.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/repository/IServicioRepository.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/service/IEmpleadoService.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/service/IServicioService.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/service/imp/EmpleadoServiceMysqlImp.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/service/imp/ServicioServiceImp.java
  Tp2_Grupo30/src/main/java/ar/edu/unju/fi/service/imp/ServicioServiceMysqlImp.java
  Tp2_Grupo30/src/main/resources/messages.properties
  Tp2_Grupo30/src/main/resources/templates/empleados.html
  Tp2_Grupo30/src/main/resources/templates/gestion_datos.html
  Tp2_Grupo30/src/main/resources/templates/gestion_empleados.html
  Tp2_Grupo30/src/main/resources/templates/gestion_servicios.html
  Tp2_Grupo30/src/main/resources/templates/nuevo_empleado.html
  Tp2_Grupo30/src/main/resources/templates/nuevo_servicio.html
  Tp2_Grupo30/src/main/resources/templates/servicios.html
Labels: Fusión de ramas
